import { BLACK, BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import {
  black,
  city,
  DARK_MOUNTAIN,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  white,
} from "../factory";
import z from "zod";
import { PlayerColorZod } from "../../engine/state/player";
import { CityData, LandData } from "../../engine/state/space";

export const DoubleBaseUsaMapData = z.object({
  startingCity: z.boolean().optional(),
  eastCoastCity: z.boolean().optional(),
  startingPlayer: PlayerColorZod.optional(),
  hasLandGrant: z.boolean().optional(),
});
export type DoubleBaseUsaMapData = z.infer<typeof DoubleBaseUsaMapData>;

function riverTown(name: string): LandData {
  return {
    ...RIVER,
    townName: name,
  };
}

function startingEastCostCity(name: string): CityData {
  return {
    ...city(name, undefined, undefined, 1),
    mapSpecific: {
      startingCity: true,
      eastCoastCity: true,
    },
  };
}

function cubeTown(townName: string): LandData {
  return {
    ...town(townName),
    goods: [],
  };
}

function riverCubeTown(townName: string): LandData {
  return {
    ...RIVER,
    townName: townName,
    goods: [],
  };
}

const LAND_GRANT_PLAIN: LandData = {
  ...PLAIN,
  mapSpecific: {
    hasLandGrant: true,
  },
};

export const map = grid([
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    town("Salem"),
    PLAIN,
    PLAIN,
    PLAIN,
    city("San Francisco", BLACK, undefined, 5),
    PLAIN,
    PLAIN,
  ],
  [
    RIVER,
    LAND_GRANT_PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
    town("Los Angeles"),
  ],
  [
    UNPASSABLE,
    city("Seattle", PURPLE, white(6), 2),
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    town("Reno"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    town("San Diego"),
  ],
  [
    MOUNTAIN,
    DARK_MOUNTAIN,
    LAND_GRANT_PLAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
    PLAIN,
    town("Las Vegas"),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Boise"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    LAND_GRANT_PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    LAND_GRANT_PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Phoenix", PURPLE, black(6), 2),
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    town("Helena"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    riverTown("Salt Lake City"),
    DARK_MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    DARK_MOUNTAIN,
    DARK_MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    LAND_GRANT_PLAIN,
    city("Billings", RED, white(5), 2),
    LAND_GRANT_PLAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
    MOUNTAIN,
    DARK_MOUNTAIN,
    MOUNTAIN,
    town("Santa Fe"),
    PLAIN,
    town("El Paso"),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Cheyenne"),
    PLAIN,
    city("Denver", YELLOW, black(5), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    cubeTown("Regina"),
    PLAIN,
    PLAIN,
    town("Rapid City"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
    PLAIN,
    PLAIN,
    town("Odessa"),
    PLAIN,
    LAND_GRANT_PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
    PLAIN,
    town("Amarillo"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Laredo"),
  ],
  [
    UNPASSABLE,
    LAND_GRANT_PLAIN,
    PLAIN,
    PLAIN,
    town("Yankton"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("San Antonio"),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    LAND_GRANT_PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Dallas/Ft Worth", YELLOW, black(4), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    cubeTown("Winnipeg"),
    PLAIN,
    RIVER,
    RIVER,
    PLAIN,
    cubeTown("Omaha"),
    PLAIN,
    city("Kansas City", BLUE, black(3), 2),
    PLAIN,
    cubeTown("Tulsa"),
    PLAIN,
    PLAIN,
    PLAIN,
    city("Houston", BLACK, undefined, 2),
  ],
  [
    UNPASSABLE,
    PLAIN,
    LAND_GRANT_PLAIN,
    PLAIN,
    city("Minneapolis", BLUE, white(4), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    riverTown("Duluth"),
    PLAIN,
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    PLAIN,
    PLAIN,
    RIVER,
    RIVER,
    RIVER,
  ],
  [
    UNPASSABLE,
    cubeTown("Thunder Bay"),
    RIVER,
    RIVER,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    riverCubeTown("St. Louis"),
    RIVER,
    riverCubeTown("Memphis"),
    PLAIN,
    PLAIN,
    city("New Orleans", PURPLE, black(2), 2),
  ],
  [
    UNPASSABLE,
    PLAIN,
    RIVER,
    RIVER,
    riverCubeTown("Green Bay"),
    RIVER,
    city("Chicago", BLUE, white(3), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    PLAIN,
    cubeTown("Indianapolis"),
    PLAIN,
    cubeTown("Nashville"),
    PLAIN,
    PLAIN,
    cubeTown("Mobile"),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    riverCubeTown("Sault Ste. Marie"),
    RIVER,
    RIVER,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    RIVER,
    RIVER,
    riverCubeTown("Detroit"),
    PLAIN,
    PLAIN,
    city("Cincinnati", RED, white(2), 2),
    MOUNTAIN,
    PLAIN,
    city("Atlanta", YELLOW, black(1), 2),
    PLAIN,
    cubeTown("Tallahassee"),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    riverCubeTown("Toronto"),
    RIVER,
    RIVER,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    cubeTown("Tampa"),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    RIVER,
    RIVER,
    city("Pittsburgh", YELLOW, white(1), 2),
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    cubeTown("Charlotte"),
    PLAIN,
    PLAIN,
    startingEastCostCity("Jacksonville"),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city("Montreal", BLACK, undefined, 2),
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    cubeTown("Richmond"),
    PLAIN,
    PLAIN,
    startingEastCostCity("Charleston"),
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    cubeTown("Miami"),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    cubeTown("Harrisburg"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    cubeTown("Montpelier"),
    PLAIN,
    cubeTown("Scranton"),
    PLAIN,
    PLAIN,
    startingEastCostCity("Baltimore"),
    PLAIN,
    startingEastCostCity("Norfolk"),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    startingEastCostCity("Philadelphia"),
  ],
  [
    UNPASSABLE,
    PLAIN,
    startingEastCostCity("Portland"),
    PLAIN,
    startingEastCostCity("Boston"),
    PLAIN,
    startingEastCostCity("New York City"),
  ],
]);
