import { Good } from "../../engine/state/good";
import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  WATER,
  white,
} from "../factory";
import { CityData, LandData } from "../../engine/state/space";
import z from "zod";

export const EasternUsAndCanadaMapData = z.object({
  startingCity: z.boolean().optional(),
  expansionCity: z.boolean().optional(),
});
export type EasternUsAndCanadaMapData = z.infer<
  typeof EasternUsAndCanadaMapData
>;

function riverTown(name: string): LandData {
  return {
    ...RIVER,
    townName: name,
  };
}

function startingCity(city: CityData): CityData {
  return {
    ...city,
    mapSpecific: {
      startingCity: true,
    },
  };
}

function expansionCity(city: CityData): CityData {
  return {
    ...city,
    mapSpecific: {
      expansionCity: true,
    },
  };
}

export const map = grid([
  [
    ...duplicate(5, UNPASSABLE),
    ...duplicate(10, PLAIN),
    city("Kansas City", Good.PURPLE, white(3), 3),
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    ...duplicate(2, PLAIN),
    city("Minneapolis", Good.BLUE, white(5), 3),
    ...duplicate(7, PLAIN),
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    city("Duluth", Good.PURPLE, white(6), 3),
    ...duplicate(2, PLAIN),
    RIVER,
    ...duplicate(3, PLAIN),
    city("Des Moines", Good.BLUE, white(4), 3),
    ...duplicate(3, PLAIN),
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    WATER,
    PLAIN,
    PLAIN,
    RIVER,
    ...duplicate(6, PLAIN),
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    WATER,
    ...duplicate(2, PLAIN),
    town("La Crosse"),
    ...duplicate(5, RIVER),
    PLAIN,
    PLAIN,
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    ...duplicate(6, PLAIN),
    town("Rock Island"),
    PLAIN,
    RIVER,
    city("St. Louis", Good.RED, white(2), 3),
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    ...duplicate(8, PLAIN),
    town("Springfield"),
    RIVER,
    RIVER,
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    PLAIN,
    town("Green Bay"),
    PLAIN,
    town("Milwaukee"),
    PLAIN,
    city("Chicago", Good.RED, white(1), 3),
    ...duplicate(4, PLAIN),
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    ...duplicate(6, WATER),
    PLAIN,
    PLAIN,
    town("Terre Haute"),
    PLAIN,
    PLAIN,
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    ...duplicate(5, WATER),
    town("Michigan City"),
    PLAIN,
    PLAIN,
    PLAIN,
    city("Evansville", Good.BLUE, black(1), 3),
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    WATER,
    PLAIN,
    PLAIN,
    town("Grand Rapids"),
    ...duplicate(4, PLAIN),
    town("Indianapolis"),
    PLAIN,
    RIVER,
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    WATER,
    ...duplicate(5, PLAIN),
    town("Fort Wayne"),
    PLAIN,
    PLAIN,
    RIVER,
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    ...duplicate(3, WATER),
    PLAIN,
    PLAIN,
    town("Toledo"),
    PLAIN,
    PLAIN,
    city("Cincinnati", Good.BLUE, black(2), 3),
    RIVER,
    PLAIN,
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    ...duplicate(3, WATER),
    city("Detroit", Good.RED, black(3), 3),
    WATER,
    ...duplicate(3, PLAIN),
    RIVER,
    town("Lexington"),
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    WATER,
    ...duplicate(3, PLAIN),
    WATER,
    ...duplicate(3, PLAIN),
    RIVER,
    PLAIN,
    MOUNTAIN,
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    ...duplicate(3, PLAIN),
    WATER,
    town("Cleveland"),
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    MOUNTAIN,
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    PLAIN,
    expansionCity(city("Toronto", Good.YELLOW, black(6), 3)),
    RIVER,
    WATER,
    PLAIN,
    PLAIN,
    RIVER,
    RIVER,
    expansionCity(city("Wheeling", Good.YELLOW, black(4), 3)),
    MOUNTAIN,
    MOUNTAIN,
    ...duplicate(6, UNPASSABLE),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    PLAIN,
    WATER,
    town("Buffalo"),
    PLAIN,
    MOUNTAIN,
    expansionCity(city("Pittsburgh", Good.RED, black(5), 3)),
    ...duplicate(4, MOUNTAIN),
    ...duplicate(6, UNPASSABLE),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    WATER,
    town("Rochester"),
    ...duplicate(9, MOUNTAIN),
    town("Charlotte"),
    PLAIN,
    town("Columbia"),
    PLAIN,
    startingCity(city("Savannah", Good.RED, undefined, 3)),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    town("Ottawa"),
    RIVER,
    WATER,
    town("Syracuse"),
    ...duplicate(8, MOUNTAIN),
    ...duplicate(6, PLAIN),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    RIVER,
    RIVER,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    town("Lewistown"),
    MOUNTAIN,
    town("Lancaster"),
    ...duplicate(5, PLAIN),
    town("Raleigh"),
    PLAIN,
    PLAIN,
    PLAIN,
    startingCity(city("Charleston", Good.BLUE, undefined, 3)),
    WATER,
  ],
  [
    PLAIN,
    RIVER,
    riverTown("Montreal"),
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    startingCity(city("Washington, D.C.", Good.RED, undefined, 3)),
    town("Fredericksburg"),
    startingCity(city("Richmond", Good.PURPLE, undefined, 3)),
    PLAIN,
    PLAIN,
    PLAIN,
    startingCity(city("Wilmington", Good.YELLOW, undefined, 3)),
    WATER,
    WATER,
    WATER,
  ],
  [
    startingCity(city("Quebec", Good.RED, undefined, 3)),
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    town("Albany"),
    MOUNTAIN,
    town("Scranton"),
    PLAIN,
    town("Newark"),
    startingCity(city("Trenton", Good.RED, undefined, 3)),
    startingCity(city("Philadelphia", Good.BLUE, undefined, 3)),
    startingCity(city("Baltimore", Good.BLUE, undefined, 3)),
    WATER,
    RIVER,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    WATER,
    WATER,
    WATER,
    WATER,
  ],
  [
    ...duplicate(7, MOUNTAIN),
    startingCity(city("New York City", Good.PURPLE, undefined, 3)),
    WATER,
    PLAIN,
    WATER,
    town("Dover"),
    WATER,
    WATER,
    town("Chesapeake"),
    RIVER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
  ],
  [
    UNPASSABLE,
    ...duplicate(4, MOUNTAIN),
    town("Springfield"),
    PLAIN,
    startingCity(city("New Haven", Good.YELLOW, undefined, 3)),
    ...duplicate(14, WATER),
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    town("Portland"),
    PLAIN,
    startingCity(city("Boston", Good.BLUE, undefined, 3)),
    town("Providence"),
    ...duplicate(14, WATER),
  ],
]);
