import { SpaceData } from "../../engine/state/space";
import { duplicate } from "../../utils/functions";
import {
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  white,
} from "../factory";

export const map = grid<SpaceData>([
  [
    PLAIN,
    PLAIN,
    town("Winfield"),
    PLAIN,
    town("Tuscaloosa"),
    RIVER,
    ...duplicate(5, PLAIN),
  ],
  [
    town("Decatur"),
    ...duplicate(3, PLAIN),
    RIVER,
    PLAIN,
    town("Thomasville"),
    PLAIN,
    PLAIN,
    city("Mobile", [], [white(5), white(6)]),
    PLAIN,
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    RIVER,
    RIVER,
    PLAIN,
    PLAIN,
    ...duplicate(4, RIVER),
  ],
  [
    city("Huntsville", [], [white(1), white(2)]),
    MOUNTAIN,
    RIVER,
    city("Birmingham", [], white(3)),
    PLAIN,
    town("Selma"),
    RIVER,
    PLAIN,
    town("Brewton"),
  ],
  [
    MOUNTAIN,
    RIVER,
    town("Ashville"),
    PLAIN,
    PLAIN,
    RIVER,
    RIVER,
    town("Greenville"),
    PLAIN,
    PLAIN,
  ],
  [
    town("Scottsboro"),
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    city("Montgomery", [], white(4)),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    town("Heflin"),
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Troy"),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    town("Lafayette"),
    PLAIN,
    PLAIN,
    PLAIN,
    town("Dothan"),
  ],
]);
