import { SpaceData, LandData } from "../../engine/state/space";
import { Good } from "../../engine/state/good";
import { duplicate } from "../../utils/functions";
import { SpaceStyle } from "../../engine/state/location_style";
import { SpaceType } from "../../engine/state/location_type";

import {
  black,
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  white,
} from "../factory";

const CANYON : LandData = {
  type: SpaceType.UNPASSABLE,
  style: SpaceStyle.CANYON,
};


export const map = grid<SpaceData>([
  [UNPASSABLE, ...duplicate(4, PLAIN), RIVER, ...duplicate(9, PLAIN)],
  [
    ...duplicate(4, PLAIN),
    RIVER,
    RIVER,
    city("Cedar City", Good.PURPLE, white(3), 2),
    PLAIN,
    CANYON,
    CANYON,
    PLAIN,
    town("Prescott"),
    PLAIN,
    city("Phoenix", Good.RED, black(2), 2),
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    city("Twin Falls", Good.PURPLE, white(1), 2),
    UNPASSABLE,
    PLAIN,
    PLAIN,
    RIVER,
    RIVER,
    CANYON,
    CANYON,
    RIVER,
    ...duplicate(4, PLAIN),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    RIVER,
    RIVER,
    CANYON,
    CANYON,
    city("Flagstaff", Good.RED, black(1), 2),
    ...duplicate(3, PLAIN),
    town("Tuscon"),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    town("Logan"),
    UNPASSABLE,
    city("Salt Lake City", Good.PURPLE, white(2), 2),
    RIVER,
    town("Mt.Pleasant"),
    RIVER,
    CANYON,
    PLAIN,
    RIVER,
    ...duplicate(3, PLAIN),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    ...duplicate(5, RIVER),
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
    RIVER,
    city("Show Low", Good.RED, black(3), 2),
    PLAIN,
    RIVER,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    town("Rock Springs"),
    MOUNTAIN,
    MOUNTAIN,
    town("Grand Junction"),
    ...duplicate(4, MOUNTAIN),
    town("Gallup"),
    RIVER,
    PLAIN,
    RIVER,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    ...duplicate(5, MOUNTAIN),
    town("Durango"),
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
    RIVER,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    town("Riverton"),
    MOUNTAIN,
    MOUNTAIN,
    city("Saratoga", Good.YELLOW, white(5), 2),
    ...duplicate(5, MOUNTAIN),
    RIVER,
    PLAIN,
    PLAIN,
    city("San Antonio", Good.BLUE, black(6), 2),
  ],
  [
    UNPASSABLE,
    ...duplicate(9, MOUNTAIN),
    PLAIN,
    city("Albuquerque", Good.BLUE, black(5), 2),
    PLAIN,
    RIVER,
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    city("Casper", Good.YELLOW, white(4), 2),
    ...duplicate(6, MOUNTAIN),
    city("Santa Fe", Good.BLUE, black(4), 2),
    PLAIN,
    RIVER,
    PLAIN,
    RIVER,
  ],
  [
    ...duplicate(3, RIVER),
    town("Cheyenne"),
    MOUNTAIN,
    city("Denver", Good.YELLOW, white(6), 2),
    ...duplicate(3, MOUNTAIN),
    PLAIN,
    RIVER,
    town("Santa Rosa"),
    RIVER,
  ],
  [UNPASSABLE, ...duplicate(9, MOUNTAIN), RIVER, ...duplicate(3, PLAIN)],
]);
