import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { SpaceType } from "../../engine/state/location_type";
import { CityData } from "../../engine/state/space";
import {
  BOTTOM,
  BOTTOM_LEFT,
  BOTTOM_RIGHT,
  TOP,
  TOP_LEFT,
  TOP_RIGHT,
} from "../../engine/state/tile";
import { duplicate } from "../../utils/functions";
import {
  black,
  bridge,
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  WATER,
  white,
} from "../factory";
import { startFrom } from "../tile_factory";
import { HEAVY_CARDBOARD_SAME_CITY } from "./heavy_cardboard_city";

const HEAVY_CARDBOARD_CITY: CityData = {
  type: SpaceType.CITY,
  sameCity: HEAVY_CARDBOARD_SAME_CITY,
  color: [],
  name: "",
  goods: [],
  onRoll: [],
  startingNumCubes: 0,
};

export const map = grid([
  [...duplicate(7, PLAIN), town("1846"), ...duplicate(3, PLAIN)],
  [
    PLAIN,
    city("Through the Ages", BLUE, black(1)),
    ...duplicate(3, PLAIN),
    city("Die Macher", YELLOW, black(3)),
    ...duplicate(3, PLAIN),
    city("Agricola", YELLOW, black(4)),
    MOUNTAIN,
  ],
  [
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    town("Pax Renaissance"),
    PLAIN,
    PLAIN,
    town("Dominant Species"),
    PLAIN,
    PLAIN,
    MOUNTAIN,
  ],
  [UNPASSABLE, MOUNTAIN, MOUNTAIN, ...duplicate(5, PLAIN), MOUNTAIN, MOUNTAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    ...duplicate(3, MOUNTAIN),
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    town("Three Kingdoms Redux"),
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    city("Arkwright", RED, black(5)),
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    PLAIN,
    MOUNTAIN,
    city("1822", PURPLE, black(2)),
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    town("Tramways"),
    MOUNTAIN,
  ],
  [
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    { ...MOUNTAIN, unpassableEdges: [BOTTOM, BOTTOM_RIGHT] },
    HEAVY_CARDBOARD_CITY,
    HEAVY_CARDBOARD_CITY,
    { ...MOUNTAIN, unpassableEdges: [TOP, TOP_RIGHT] },
    town("Vinhos"),
    ...duplicate(3, PLAIN),
  ],
  [
    town("Puerto Rico"),
    PLAIN,
    PLAIN,
    MOUNTAIN,
    HEAVY_CARDBOARD_CITY,
    {
      ...HEAVY_CARDBOARD_CITY,
      name: "Heavy Cardboard",
      mapSpecific: { center: true },
    },
    HEAVY_CARDBOARD_CITY,
    MOUNTAIN,
    ...duplicate(3, PLAIN),
  ],
  [
    bridge({
      tile: {
        ...startFrom(TOP_LEFT).curveLeft(),
        claimableCost: [6],
      },
    }),
    WATER,
    RIVER,
    { ...RIVER, unpassableEdges: [BOTTOM_LEFT, BOTTOM] },
    HEAVY_CARDBOARD_CITY,
    HEAVY_CARDBOARD_CITY,
    { ...PLAIN, unpassableEdges: [TOP, TOP_LEFT] },
    ...duplicate(3, PLAIN),
    city("Le Havre", RED, black(6)),
  ],
  [
    city("Madeira", [BLUE, RED], white(6)),
    WATER,
    PLAIN,
    RIVER,
    PLAIN,
    RIVER,
    ...duplicate(3, PLAIN),
    RIVER,
    RIVER,
  ],
  [
    bridge({
      tile: {
        ...startFrom(TOP_LEFT).curveLeft(),
        claimableCost: [6],
      },
    }),
    PLAIN,
    town("Wildcatters"),
    RIVER,
    PLAIN,
    RIVER,
    PLAIN,
    city("Food Chain Magnate", YELLOW, white(3)),
    RIVER,
    town("The Great Zimbabwe"),
    PLAIN,
  ],
  [
    town("Container"),
    RIVER,
    RIVER,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    ...duplicate(4, RIVER),
    PLAIN,
  ],
  [
    RIVER,
    PLAIN,
    RIVER,
    city("Brass", RED, white(4)),
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    town("Antiquity"),
    RIVER,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    RIVER,
    RIVER,
    PLAIN,
    MOUNTAIN,
    UNPASSABLE,
    MOUNTAIN,
    PLAIN,
    RIVER,
    PLAIN,
    city("Age of Steam", BLUE, white(1)),
  ],
  [
    city("Lisboa", PURPLE, white(5)),
    PLAIN,
    town("Lignum"),
    MOUNTAIN,
    UNPASSABLE,
    UNPASSABLE,
    MOUNTAIN,
    PLAIN,
    RIVER,
    RIVER,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    MOUNTAIN,
    city("Indonesia", YELLOW, white(2)),
    PLAIN,
    RIVER,
  ],
]);
