import {
  black,
  city,
  grid,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  white,
} from "../factory";
import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";

// FIXME: See how we can tweak this to have some custom styling
const CENTRAL_LONDON_PLAIN = PLAIN;
const CENTRAL_LONDON_RIVER = RIVER;

export const map = grid([
  [
    city("Ruislip", [BLUE], white(1), 4),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Feltham"),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    town("Greerford"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Twickenham", [RED], white(2), 4),
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Hanwell"),
    PLAIN,
    town("Isleworth"),
    PLAIN,
    RIVER,
    PLAIN,
  ],
  [
    PLAIN,
    city("Webley", [YELLOW], white(3), 3),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    RIVER,
    RIVER,
    RIVER,
  ],
  [
    town("Kenton"),
    PLAIN,
    PLAIN,
    town("Park Royal"),
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Chiswick"),
    RIVER,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("North Kensington", [PURPLE], white(4), 3),
    PLAIN,
    RIVER,
    RIVER,
    PLAIN,
    PLAIN,
    city("Wimbledon", [YELLOW], white(5), 3),
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Fulham"),
    PLAIN,
    town("Putney"),
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    town("Camden"),
    PLAIN,
    town("St. John's Wood"),
    PLAIN,
    PLAIN,
    RIVER,
    RIVER,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    CENTRAL_LONDON_PLAIN,
    CENTRAL_LONDON_PLAIN,
    CENTRAL_LONDON_PLAIN,
    city("Westminster", [PURPLE], white(6), 3),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    town("Tottenham"),
    PLAIN,
    CENTRAL_LONDON_PLAIN,
    city("Bloomsbury", [BLUE], black(1), 3),
    CENTRAL_LONDON_PLAIN,
    city("Waterloo", [RED], black(2), 3),
    CENTRAL_LONDON_RIVER,
    town("Brixton"),
    PLAIN,
    town("Streatham"),
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    city("Shoreditch", [RED], black(3), 3),
    CENTRAL_LONDON_PLAIN,
    CENTRAL_LONDON_RIVER,
    CENTRAL_LONDON_PLAIN,
    CENTRAL_LONDON_PLAIN,
    CENTRAL_LONDON_PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    CENTRAL_LONDON_RIVER,
    town("Deptford"), // FIXME: central london styling
    PLAIN,
    town("Forest Hill"),
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    CENTRAL_LONDON_RIVER,
    CENTRAL_LONDON_RIVER,
    CENTRAL_LONDON_PLAIN,
    PLAIN,
    PLAIN,
    town("Beckenham"),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    RIVER,
    CENTRAL_LONDON_RIVER,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    town("West Ham"),
    PLAIN,
    RIVER,
    RIVER,
    PLAIN,
    town("Mottingham"),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    city("Greenwich", [PURPLE], black(4), 3),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    city("Ilford", [BLUE], black(5), 4),
    PLAIN,
    PLAIN,
    PLAIN,
    town("Woolwich"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("St. Paul's Clay", [RED], black(6), 4),
  ],
]);
