import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { SpaceData } from "../../engine/state/space";
import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  MOUNTAIN,
  PLAIN,
  startsLowerGrid,
  town,
  UNPASSABLE,
  white,
} from "../factory";

export const map = startsLowerGrid<SpaceData>([
  [
    PLAIN,
    PLAIN,
    town("Saratoga"),
    PLAIN,
    PLAIN,
    PLAIN,
    city("Schenectady", BLUE, [black(3), black(4)], 3),
    PLAIN,
    PLAIN,
    PLAIN,
    city("New York", RED, [black(5), black(6)], 3),
  ],
  [
    city("Burlington", PURPLE, black(1), 3),
    ...duplicate(4, MOUNTAIN),
    town("Bennington"),
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
  ],
  [
    MOUNTAIN,
    town("Montpelier"),
    PLAIN,
    town("Rutland"),
    ...duplicate(3, MOUNTAIN),
    PLAIN,
    PLAIN,
    city("New Haven", RED, black(2), 3),
  ],
  [
    PLAIN,
    PLAIN,
    MOUNTAIN,
    ...duplicate(3, PLAIN),
    town("Springfield"),
    PLAIN,
    town("Hartford"),
    PLAIN,
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    city("Concord", BLUE, white(3), 3),
    ...duplicate(6, PLAIN),
  ],
  [
    MOUNTAIN,
    town("Berlin"),
    ...duplicate(3, MOUNTAIN),
    city("Manchester", BLUE, white(2), 3),
    PLAIN,
    PLAIN,
    city("Providence", BLUE, white(4), 3),
    PLAIN,
  ],
  [
    ...duplicate(3, MOUNTAIN),
    ...duplicate(3, PLAIN),
    city("Boston", RED, [white(5), white(6)], 3),
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    town("Augusta"),
    PLAIN,
    city("Portland", YELLOW, white(1), 3),
    PLAIN,
    ...duplicate(3, UNPASSABLE),
    town("New Bedford"),
  ],
]);
