import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { SpaceData } from "../../engine/state/space";
import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  MOUNTAIN,
  PLAIN,
  startsLowerGrid,
  town,
  UNPASSABLE,
  white,
} from "../factory";

export const map = startsLowerGrid<SpaceData>([
  [
    PLAIN,
    PLAIN,
    town("?"),
    PLAIN,
    PLAIN,
    PLAIN,
    city("b", BLUE, [black(3), black(4)], 3),
    PLAIN,
    PLAIN,
    PLAIN,
    city("New York", RED, [black(5), black(6)], 3),
  ],
  [
    city("c", PURPLE, black(1), 3),
    ...duplicate(4, MOUNTAIN),
    town("?"),
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
  ],
  [
    MOUNTAIN,
    town("?"),
    PLAIN,
    town("?"),
    ...duplicate(3, MOUNTAIN),
    PLAIN,
    PLAIN,
    city("New Haven", RED, black(2), 3),
  ],
  [
    PLAIN,
    PLAIN,
    MOUNTAIN,
    ...duplicate(3, PLAIN),
    town("?"),
    PLAIN,
    town("?"),
    PLAIN,
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    city("d", BLUE, white(3), 3),
    ...duplicate(6, PLAIN),
  ],
  [
    MOUNTAIN,
    town("?"),
    ...duplicate(3, MOUNTAIN),
    city("e", BLUE, white(2), 3),
    PLAIN,
    PLAIN,
    city("f", BLUE, white(4), 3),
    PLAIN,
  ],
  [
    ...duplicate(3, MOUNTAIN),
    ...duplicate(3, PLAIN),
    city("p", RED, [white(5), white(6)], 3),
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    town("?"),
    PLAIN,
    city("r", YELLOW, white(1), 3),
    PLAIN,
    ...duplicate(3, UNPASSABLE),
    town("?"),
  ],
]);
