import { BLACK, WHITE } from '../../engine/state/city_group';
import { BLUE, Good, PURPLE, RED, YELLOW } from '../../engine/state/good';
import { duplicate } from '../../utils/functions';
import { city, grid, MOUNTAIN, PLAIN, RIVER, town, UNPASSABLE } from '../factory';

export const map = grid([
  [
    city('Scotland', [RED, BLUE], BLACK, 1),
    UNPASSABLE,
    PLAIN,
    town('Coleraine'),
    UNPASSABLE,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    city('Londonderry', Good.BLACK, WHITE, 1),
    PLAIN,
    city('Glenties', []),
  ],
  [
    UNPASSABLE,
    city('Belfast', PURPLE, WHITE, 2),
    PLAIN,
    PLAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    town('Armagh'),
    PLAIN,
    town('Enniskillen'),
    PLAIN,
    city('Sligo', []),
  ],
  [
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    RIVER,
    PLAIN,
    town('Ballina'),
    PLAIN,
  ],
  [
    UNPASSABLE,
    city('Dundalk', PURPLE, WHITE, 3),
    PLAIN,
    town('Cavan'),
    PLAIN,
    RIVER,
    town('Castlerea'),
    PLAIN,
    PLAIN,
    city('Westport'),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    city('Wales', [RED, BLUE], BLACK, 2),
    UNPASSABLE,
    PLAIN,
    town('Mullingar'),
    PLAIN,
    city('Athlone'),
    PLAIN,
    town('Galway'),
    PLAIN,
    city('Clifden'),
  ],
  [
    UNPASSABLE,
    city('Dublin', PURPLE, WHITE, 4),
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    MOUNTAIN,
    PLAIN,
    town('Port Laoise'),
    PLAIN,
    RIVER,
    PLAIN,
  ],
  [
    UNPASSABLE,
    town('Wicklow'),
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    city('Limerick', PURPLE, WHITE, 5),
    PLAIN,
    city('Ballyunion'),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    town('Tipperary'),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    city('Rosslare'),
    PLAIN,
    city('Waterford'),
    PLAIN,
    MOUNTAIN,
    PLAIN,
    MOUNTAIN,
    town('Tralee'),
    PLAIN,
  ],
  [
    ...duplicate(4, UNPASSABLE),
    PLAIN,
    PLAIN,
    city('Cork', Good.BLACK, WHITE, 6),
    MOUNTAIN,
    PLAIN,
    PLAIN,
    city('Valentia'),
  ],
  [
    PLAIN,
    city('England', YELLOW),
    ...duplicate(4, UNPASSABLE),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city('England', YELLOW),
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city('Bantry'),
  ],
]);
