import { BLACK, BLUE, Good, PURPLE, RED, YELLOW } from '../../engine/state/good';
import { Direction } from '../../engine/state/tile';
import { duplicate } from '../../utils/functions';
import { black, city, grid, MOUNTAIN, plain, PLAIN, RIVER, town, UNPASSABLE, white } from '../factory';

export const map = grid([
  [
    city('Scotland', [RED, BLUE], black(1)),
    UNPASSABLE,
    PLAIN,
    town('Coleraine'),
    UNPASSABLE,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    city('Londonderry', BLACK, white(1)),
    PLAIN,
    city('Glenties', [], [], 3),
  ],
  [
    UNPASSABLE,
    city('Belfast', PURPLE, white(2)),
    PLAIN,
    PLAIN,
    MOUNTAIN,
    plain({ unpassableEdges: [Direction.BOTTOM_RIGHT] }),
    plain({ unpassableEdges: [Direction.TOP_RIGHT] }),
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    town('Armagh'),
    PLAIN,
    town('Enniskillen'),
    PLAIN,
    city('Sligo', [], [], 3),
  ],
  [
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    RIVER,
    PLAIN,
    town('Ballina'),
    PLAIN,
  ],
  [
    UNPASSABLE,
    city('Dundalk', PURPLE, white(3)),
    PLAIN,
    town('Cavan'),
    PLAIN,
    RIVER,
    town('Castlerea'),
    PLAIN,
    PLAIN,
    city('Westport', [], [], 3),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
    plain({ unpassableEdges: [Direction.BOTTOM, Direction.BOTTOM_RIGHT] }),
    plain({ unpassableEdges: [Direction.BOTTOM_LEFT] }),
  ],
  [
    city('Wales', [RED, BLUE], black(2)),
    UNPASSABLE,
    PLAIN,
    town('Mullingar'),
    PLAIN,
    city('Athlone', [], [], 3),
    PLAIN,
    town('Galway'),
    PLAIN,
    city('Clifden', [], [], 3),
  ],
  [
    UNPASSABLE,
    city('Dublin', PURPLE, white(4)),
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    MOUNTAIN,
    PLAIN,
    town('Port Laoise'),
    PLAIN,
    RIVER,
    PLAIN,
  ],
  [
    UNPASSABLE,
    town('Wicklow'),
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    city('Limerick', PURPLE, white(5)),
    plain({ unpassableEdges: [Direction.TOP_RIGHT, Direction.BOTTOM_RIGHT] }),
    city('Ballyunion', [], [], 3),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    town('Tipperary'),
    PLAIN,
    PLAIN,
    plain({ unpassableEdges: [Direction.BOTTOM_LEFT] }),
  ],
  [
    UNPASSABLE,
    city('Rosslare', [], [], 2),
    PLAIN,
    city('Waterford', [], [], 2),
    PLAIN,
    MOUNTAIN,
    PLAIN,
    MOUNTAIN,
    town('Tralee'),
    plain({ unpassableEdges: [Direction.TOP_RIGHT, Direction.BOTTOM_RIGHT] }),
  ],
  [
    ...duplicate(4, UNPASSABLE),
    PLAIN,
    PLAIN,
    city('Cork', Good.BLACK, white(6)),
    MOUNTAIN,
    PLAIN,
    plain({ unpassableEdges: [Direction.TOP_RIGHT] }),
    city('Valentia', [], [], 3),
  ],
  [
    PLAIN,
    city('England', YELLOW),
    ...duplicate(4, UNPASSABLE),
    PLAIN,
    PLAIN,
    plain({ unpassableEdges: [Direction.TOP_RIGHT] }),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city('England', YELLOW),
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city('Bantry', [], [], 3),
  ],
]);
