import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  white,
} from "../factory";
import z from "zod";
import { LandData } from "../../engine/state/space";
import { BLACK, BLUE, PURPLE, RED } from "../../engine/state/good";

export const CaliforniaGoldRushMapData = z.object({
  goldLocation: z.boolean().optional(),
});
export type CaliforniaGoldRushMapData = z.infer<
  typeof CaliforniaGoldRushMapData
>;

const GOLD_MOUNTAIN: LandData = {
  ...MOUNTAIN,
  mapSpecific: {
    goldLocation: true,
  },
};

export const map = grid([
  [...duplicate(15, UNPASSABLE)],
  [UNPASSABLE, UNPASSABLE, PLAIN, PLAIN, ...duplicate(11, UNPASSABLE)],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    city("Eureka", BLACK, white(2), 2),
    PLAIN,
    PLAIN,
    town("Ukiah"),
    PLAIN,
    PLAIN,
    PLAIN,
    ...duplicate(5, UNPASSABLE),
  ],
  [
    city("Crescent City", RED, white(1), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Lakeport", BLACK, white(5), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    city("San Francisco", PURPLE, black(1), 2),
    PLAIN,
    PLAIN,
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    GOLD_MOUNTAIN,
    GOLD_MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("San Jose", RED, black(2), 2),
  ],
  [
    GOLD_MOUNTAIN,
    GOLD_MOUNTAIN,
    GOLD_MOUNTAIN,
    GOLD_MOUNTAIN,
    town("Red Bluff"),
    MOUNTAIN,
    town("Willows"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    MOUNTAIN,
    PLAIN,
    PLAIN,
  ],
  [
    town("Yreka"),
    MOUNTAIN,
    RIVER,
    town("Redding"),
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    town("Yuba City"),
    RIVER,
    city("Sacramento", RED, white(6), 2),
    GOLD_MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    town("Salinas"),
  ],
  [
    PLAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    GOLD_MOUNTAIN,
    MOUNTAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    town("Modesto"),
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    town("Big Lake"),
    PLAIN,
    GOLD_MOUNTAIN,
    GOLD_MOUNTAIN,
    town("Downieville"),
    MOUNTAIN,
    MOUNTAIN,
    GOLD_MOUNTAIN,
    GOLD_MOUNTAIN,
    MOUNTAIN,
    GOLD_MOUNTAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    GOLD_MOUNTAIN,
    MOUNTAIN,
    GOLD_MOUNTAIN,
    GOLD_MOUNTAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    city("Susanville", PURPLE, white(4), 2),
    RIVER,
    MOUNTAIN,
    GOLD_MOUNTAIN,
    MOUNTAIN,
    town("Markleeville"),
    PLAIN,
    PLAIN,
    PLAIN,
    town("Fresno"),
  ],
  [
    PLAIN,
    city("Alturas", BLUE, white(3), 3),
    PLAIN,
    PLAIN,
    MOUNTAIN,
    RIVER,
    MOUNTAIN,
    GOLD_MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    GOLD_MOUNTAIN,
    GOLD_MOUNTAIN,
    city("Tonivia", BLUE, black(3), 2),
    PLAIN,
    PLAIN,
  ],
]);
