import { CityGroup } from "../../engine/state/city_group";
import { Good } from "../../engine/state/good";
import { LocationType } from "../../engine/state/location_type";
import { LocationData } from "../../engine/state/space";
import { duplicate } from "../../utils/functions";
import { city, grid, MOUNTAIN, PLAIN, RIVER, town, UNPASSABLE } from "../factory";

const { WHITE, BLACK } = CityGroup;

const SWAMP: LocationData = {
  type: LocationType.SWAMP,
};

export const map = grid([
  [
    ...duplicate(4, UNPASSABLE),
    MOUNTAIN,
    UNPASSABLE,
    MOUNTAIN,
    town('Chihuahua'),
    ...duplicate(3, PLAIN),
    town('Houston'),
    PLAIN,
    SWAMP,
    city('New Orleans', Good.BLUE, BLACK, 6),
  ],
  [
    ...duplicate(3, UNPASSABLE),
    MOUNTAIN,
    UNPASSABLE,
    MOUNTAIN,
    ...duplicate(6, PLAIN),
    SWAMP,
    RIVER,
  ],
  [
    ...duplicate(3, UNPASSABLE),
    town('San Diego'),
    PLAIN,
    town('Yuma'),
    MOUNTAIN,
    PLAIN,
    town('El Paso'),
    PLAIN,
    PLAIN,
    town('Fort Worth'),
    SWAMP,
    SWAMP,
    city('Vicksburg', Good.BLUE, BLACK, 5),
  ],
  [
    UNPASSABLE,
    city('Los Angeles', Good.RED, WHITE, 1),
    MOUNTAIN,
    PLAIN,
    ...duplicate(3, MOUNTAIN),
    ...duplicate(5, PLAIN),
    SWAMP,
    RIVER,
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    MOUNTAIN,
    PLAIN,
    MOUNTAIN,
    town('Santa Fe'),
    PLAIN,
    PLAIN,
    town('Amarillo'),
    PLAIN,
    SWAMP,
    SWAMP,
    city('Memphis', Good.BLUE, BLACK, 4),
  ],
  [
    city('San Francisco', Good.PURPLE, WHITE, 2),
    PLAIN,
    MOUNTAIN,
    PLAIN,
    MOUNTAIN,
    town('Durango'),
    MOUNTAIN,
    MOUNTAIN,
    town('Trinidad'),
    ...duplicate(3, PLAIN),
    SWAMP,
    RIVER,
  ],
  [
    UNPASSABLE,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    ...duplicate(4, MOUNTAIN),
    PLAIN,
    PLAIN,
    town('Wichita'),
    PLAIN,
    PLAIN,
    city('Saint Louis', Good.YELLOW, WHITE, 6),
  ],
  [
    MOUNTAIN,
    town('Sacramento'),
    MOUNTAIN,
    PLAIN,
    ...duplicate(4, MOUNTAIN),
    city('Denver', Good.PURPLE, WHITE, 5),
    ...duplicate(3, PLAIN),
    town('Kansas City'),
    RIVER,
  ], [
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    city('Salt Lake City', Good.YELLOW, WHITE, 4),
    ...duplicate(4, MOUNTAIN),
    ...duplicate(5, PLAIN),
    RIVER,
  ], [
    ...duplicate(3, MOUNTAIN),
    PLAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    town('Cheyenne'),
    PLAIN,
    PLAIN,
    town('Omaha'),
    PLAIN,
    city('Des Moines', Good.RED, BLACK, 3),
  ],
  [
    UNPASSABLE,
    town('Portland'),
    ...duplicate(6, MOUNTAIN),
    ...duplicate(5, PLAIN),
    RIVER,
    PLAIN,
  ], [
    ...duplicate(4, MOUNTAIN),
    town('Butte'),
    MOUNTAIN,
    town('Billings'),
    ...duplicate(5, PLAIN),
    city('Minneapolis', Good.RED, BLACK, 2),
    PLAIN,
  ], [
    UNPASSABLE,
    city('Seattle', Good.BLUE, WHITE, 3),
    MOUNTAIN,
    town('Spokane'),
    ...duplicate(3, MOUNTAIN),
    ...duplicate(3, PLAIN),
    town('Fargo'),
    ...duplicate(3, PLAIN),
    city('Deluth', Good.RED, BLACK, 1),
  ],
]);