import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { city, grid, PLAIN, town, UNPASSABLE } from "../factory";

export const map = grid([
  [
    UNPASSABLE,
    PLAIN,
    city("Toronto", BLUE, [], 3),
    PLAIN,
    town("London"),
    PLAIN,
    PLAIN,
    UNPASSABLE,
    town("Milwaukee"),
    PLAIN,
    UNPASSABLE,
  ],
  [
    PLAIN,
    city("Buffalo", PURPLE, [], 3),
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city("Detroit", BLUE, [], 3),
    PLAIN,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    UNPASSABLE,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Cleveland", YELLOW, [], 3),
    UNPASSABLE,
    PLAIN,
    PLAIN,
    city("Chicago", BLUE, [], 3),
    PLAIN,
    UNPASSABLE,
  ],
  [
    PLAIN,
    PLAIN,
    town("Youngstown"),
    PLAIN,
    PLAIN,
    PLAIN,
    town("Fort Wayne"),
    PLAIN,
    PLAIN,
    town("Peoria"),
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    city("Pittsburgh", [], [], 4),
    PLAIN,
    town("Columbus"),
    PLAIN,
    city("Indianapolis", RED, [], 3),
    PLAIN,
    town("Decatur"),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("St Louis", RED, [], 3),
  ],
  [
    town("Hagerstown"),
    PLAIN,
    UNPASSABLE,
    PLAIN,
    city("Cincinnati", RED, [], 3),
    PLAIN,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
  ],
]);
