import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { SpaceData } from "../../engine/state/space";
import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  MOUNTAIN,
  PLAIN,
  startsLowerGrid,
  town,
  UNPASSABLE,
  white,
} from "../factory";

export const map = startsLowerGrid<SpaceData>([
  [...duplicate(4, UNPASSABLE), MOUNTAIN, MOUNTAIN, town("Geraldton")],
  [
    ...duplicate(4, UNPASSABLE),
    city("Exmouth", PURPLE, white(2), 3),
    ...duplicate(3, MOUNTAIN),
    { ...city("Perth", BLUE, white(1), 3), mapSpecific: { bonus: 3 } },
    MOUNTAIN,
  ],
  [...duplicate(3, UNPASSABLE), ...duplicate(6, MOUNTAIN), town("Albany")],
  [
    ...duplicate(2, UNPASSABLE),
    city("Broome", YELLOW, white(3), 3),
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    ...duplicate(4, PLAIN),
    town("Kalgoorlie Boulder"),
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    town("The Kimberly"),
    ...duplicate(5, PLAIN),
    MOUNTAIN,
  ],
  [MOUNTAIN, MOUNTAIN, ...duplicate(5, PLAIN), MOUNTAIN],
  [
    city("Darwin", YELLOW, white(4), 3),
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    city("Uluru", PURPLE, white(6), 3),
    PLAIN,
    MOUNTAIN,
  ],
  [MOUNTAIN, MOUNTAIN, ...duplicate(5, PLAIN), MOUNTAIN],
  [
    MOUNTAIN,
    town("Katherine"),
    PLAIN,
    PLAIN,
    city("Alice Springs", YELLOW, white(5), 3),
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    town("Tennant Creek"),
    ...duplicate(4, PLAIN),
    town("Flinders Ranges"),
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    MOUNTAIN,
    ...duplicate(5, PLAIN),
    MOUNTAIN,
    city("Adelaide", PURPLE, black(6)),
    MOUNTAIN,
  ],
  [UNPASSABLE, MOUNTAIN, ...duplicate(5, PLAIN), ...duplicate(4, MOUNTAIN)],
  [
    ...duplicate(4, MOUNTAIN),
    ...duplicate(3, PLAIN),
    ...duplicate(3, MOUNTAIN),
    city("Melbourne", YELLOW, black(5)),
  ],
  [UNPASSABLE, city("Cairns", PURPLE, black(1)), ...duplicate(9, MOUNTAIN)],
  [
    ...duplicate(3, UNPASSABLE),
    city("Townsville", RED, black(2)),
    ...duplicate(5, MOUNTAIN),
    city("Sydney", RED, black(4)),
    MOUNTAIN,
  ],
  [
    ...duplicate(4, UNPASSABLE),
    town("Rockhampton"),
    MOUNTAIN,
    city("Brisbane", PURPLE, black(3)),
    MOUNTAIN,
    MOUNTAIN,
  ],
]);
