import { Good } from "../../engine/state/good";
import { SpaceData } from "../../engine/state/space";
import { grid } from "../factory";
import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  WATER,
  white,
  UNPASSABLE,
} from "../factory";

export const map = grid<SpaceData>([
  [
    UNPASSABLE,
    ...duplicate(2, PLAIN),
    city("Memphis", Good.RED, white(2), 1),
    ...duplicate(3, PLAIN),
    city("Jackson", Good.BLUE, white(3), 1),
    ...duplicate(3, PLAIN),
    city("New Orleans", [Good.YELLOW, Good.WHITE], white(4), 3),
  ],
  [...duplicate(10, PLAIN), WATER],
  [
    UNPASSABLE,
    PLAIN,
    town("Jackson"),
    PLAIN,
    town("Tupelo"),
    ...duplicate(2, PLAIN),
    town("Meridian"),
    ...duplicate(2, PLAIN),
    town("Biloxi"),
  ],
  [...duplicate(3, RIVER), ...duplicate(7, PLAIN)],
  [
    UNPASSABLE,
    ...duplicate(2, PLAIN),
    RIVER,
    ...duplicate(3, PLAIN),
    town("Selma"),
    RIVER,
    RIVER,
    city("Mobile", [Good.PURPLE, Good.WHITE], white(5), 3),
  ],
  [
    city("Nashville", Good.BLUE, white(1), 1),
    ...duplicate(2, PLAIN),
    town("Decatur"),
    PLAIN,
    town("Birmingham"),
    ...duplicate(4, PLAIN),
  ],
  [
    UNPASSABLE,
    ...duplicate(6, PLAIN),
    city("Montgomery", Good.BLUE, white(6), 1),
    ...duplicate(3, PLAIN),
  ],
  [MOUNTAIN, PLAIN, town("Chattanooga"), ...duplicate(8, PLAIN)],
  [
    UNPASSABLE,
    ...duplicate(3, MOUNTAIN),
    ...duplicate(3, PLAIN),
    town("Columbus"),
    ...duplicate(3, RIVER),
  ],
  [
    city("Knoxville", Good.RED, black(1), 1),
    ...duplicate(3, MOUNTAIN),
    city("Atlanta", Good.RED, black(3), 4),
    ...duplicate(4, PLAIN),
    town("Tallahassee"),
    PLAIN,
  ],
  [
    UNPASSABLE,
    ...duplicate(3, MOUNTAIN),
    ...duplicate(2, PLAIN),
    town("Macon"),
    ...duplicate(4, PLAIN),
  ],
  [...duplicate(3, MOUNTAIN), ...duplicate(9, PLAIN)],
  [
    UNPASSABLE,
    ...duplicate(2, MOUNTAIN),
    ...duplicate(2, PLAIN),
    town("Augusta"),
    ...duplicate(6, PLAIN),
  ],
  [
    PLAIN,
    town("Charlotte"),
    PLAIN,
    town("Columbia"),
    PLAIN,
    RIVER,
    ...duplicate(3, PLAIN),
    city("Jacksonville", Good.RED, black(6), 1),
    PLAIN,
  ],
  [
    UNPASSABLE,
    ...duplicate(5, PLAIN),
    RIVER,
    city("Savannah", [Good.YELLOW, Good.WHITE], black(5), 3),
  ],
  [
    city("Raleigh", Good.BLUE, black(2), 1),
    ...duplicate(4, PLAIN),
    city("Charleston", [Good.PURPLE, Good.WHITE], black(4), 3),
  ],
]);
