import { BLUE, PURPLE, RED, YELLOW } from '../../engine/state/good';
import { TOP, TOP_LEFT, TOP_RIGHT } from '../../engine/state/tile';
import { duplicate } from '../../utils/functions';
import { black, customCity, plain, PLAIN, startsLowerGrid, UNPASSABLE, white } from '../factory';
import { GREECE, TURKEY } from './roles';

export const map = startsLowerGrid([
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    customCity({ name: 'Mavroli', color: [YELLOW], onRoll: [white(1)], startingNumCubes: 2, mapSpecific: { rejects: TURKEY } }),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    customCity({ name: 'Paphos', color: [YELLOW], onRoll: [white(2)], startingNumCubes: 2, mapSpecific: { rejects: TURKEY } }),
  ],
  [
    PLAIN,
    plain({ mapSpecific: { borderDirection: [TOP, TOP_LEFT] } }),
    plain({ townName: 'Chakistra', mapSpecific: { rejects: TURKEY } }),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    plain({ townName: 'Xeros', mapSpecific: { rejects: GREECE } }),
    PLAIN,
    plain({ mapSpecific: { borderDirection: [TOP, TOP_LEFT] } }),
    PLAIN,
    PLAIN,
    plain({ townName: 'Epikopi', mapSpecific: { rejects: [TURKEY] } }),
  ],
  [
    ...duplicate(4, PLAIN),
    plain({ mapSpecific: { borderDirection: [TOP] } }),
    ...duplicate(3, PLAIN),
  ],
  [
    customCity({ name: 'Lapithos', color: [RED], onRoll: [black(1)], startingNumCubes: 2, mapSpecific: { rejects: GREECE } }),
    PLAIN,
    PLAIN,
    customCity({ name: 'Morphou', color: [BLUE], onRoll: [black(2)], startingNumCubes: 2, mapSpecific: { rejects: GREECE } }),
    plain({ mapSpecific: { borderDirection: [TOP_LEFT, TOP_RIGHT, TOP] } }),
    PLAIN,
    customCity({ name: 'Pelenétria', color: [RED], onRoll: [white(3)], startingNumCubes: 2, mapSpecific: { rejects: TURKEY } }),
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    plain({ mapSpecific: { borderDirection: [TOP] } }),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    plain({ townName: 'Kyrenia', mapSpecific: { rejects: [GREECE] } }),
    PLAIN,
    plain({ townName: 'Kato Lakatamia', mapSpecific: { rejects: [TURKEY], borderDirection: [TOP_LEFT, TOP, TOP_RIGHT] } }),
    PLAIN,
    PLAIN,
    plain({ townName: 'Limassol', mapSpecific: { rejects: [TURKEY] } }),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    plain({ mapSpecific: { borderDirection: [TOP] } }),
    ...duplicate(3, PLAIN),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    customCity({ name: 'Nikosia', color: [BLUE], onRoll: [white(6), black(6)], startingNumCubes: 2 }),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    plain({ mapSpecific: { borderDirection: [TOP, TOP_RIGHT] } }),
    PLAIN,
    PLAIN,
    customCity({ name: 'Zyyl', color: [BLUE], onRoll: [white(4)], startingNumCubes: 2, mapSpecific: { rejects: [TURKEY] } }),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    customCity({ name: 'Dhavios', color: [RED], onRoll: [black(3)], startingNumCubes: 2, mapSpecific: { rejects: [GREECE] } }),
    PLAIN,
    PLAIN,
    plain({ mapSpecific: { boderDirection: [TOP, TOP_RIGHT] } }),
    plain({ townName: 'Pane Lafkara', mapSpecific: { rejects: [TURKEY] } }),
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    plain({ townName: 'Lefkonica', mapSpecific: { rejects: [GREECE] } }),
    PLAIN,
    plain({ mapSpecific: { boderDirection: [TOP, TOP_RIGHT] } }),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    plain({ townName: 'Larnaca', mapSpecific: { rejects: [TURKEY], borderDirection: [TOP] } }),
  ],
  [
    UNPASSABLE,
    PLAIN,
    plain({ townName: 'Akanthou', mapSpecific: { rejects: GREECE } }),
    PLAIN,
    plain({ townName: 'Prastie', mapSpecific: { rejects: GREECE } }),
    plain({ mapSpecific: { borderDirection: [TOP_LEFT, TOP, TOP_RIGHT] } }),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    plain({ mapSpecific: { borderDirection: [TOP] } }),
  ],
  [
    UNPASSABLE,
    customCity({ name: 'Yialeusa', color: [PURPLE], onRoll: [black(4)], startingNumCubes: 2, mapSpecific: { rejects: [GREECE] } }),
    UNPASSABLE,
    UNPASSABLE,
    customCity({ name: 'Paralimni', color: [RED], onRoll: [white(5)], startingNumCubes: 2, mapSpecific: { rejects: [TURKEY] } }),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
  ],
  [
    plain({ townName: 'Leonarisso', mapSpecific: { rejects: GREECE } }),
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
  ],
  [
    customCity({ name: 'Rizokarpaso', color: [PURPLE], onRoll: [black(5)], startingNumCubes: 2, mapSpecific: { rejects: [GREECE] } }),
  ],
]);
