import { BLUE, PURPLE, RED } from "../../engine/state/good";
import { city, grid, PLAIN, RIVER, town, UNPASSABLE, WATER } from "../factory";
import { SpaceStyle } from "../../engine/state/location_style";
import { CityData, LandData } from "../../engine/state/space";
import z from "zod";
import { SpaceType } from "../../engine/state/location_type";

export const THE_LOOP_SAME_CITY = 1;

export const ChicagoLMapData = z.object({
  parkName: z.string().optional(),
  governmentStartingCity: z.boolean().optional(),
});
export type ChicagoLMapData = z.infer<typeof ChicagoLMapData>;

const park = (name: string): LandData => {
  return {
    ...WATER,
    style: SpaceStyle.MOUNTAIN,
    mapSpecific: {
      parkName: name,
    },
  };
};

const THE_LOOP_NORTH: CityData = {
  type: SpaceType.CITY,
  sameCity: THE_LOOP_SAME_CITY,
  color: [],
  name: "",
  goods: [],
  onRoll: [],
  startingNumCubes: 0,
};

const THE_LOOP_SOUTH: CityData = {
  type: SpaceType.CITY,
  sameCity: THE_LOOP_SAME_CITY,
  color: [],
  name: "The Loop",
  goods: [],
  onRoll: [],
  startingNumCubes: 0,
};

export const map = grid([
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    city("O'Hare", BLUE, undefined, 5),
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    city("Forest Park", BLUE, undefined, 4),
    PLAIN,
    PLAIN,
    PLAIN,
    city("Cermak", RED, undefined, 3),
    RIVER,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    park("Schiller Woods"),
    PLAIN,
    town("Harlem/Lake"),
    PLAIN,
    RIVER,
    RIVER,
    PLAIN,
    town("Cicero"),
    PLAIN,
    RIVER,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    PLAIN,
    town("Rosemont"),
    PLAIN,
    PLAIN,
    park("Christopher\nColumbus\nPark"),
    RIVER,
    town("Oak Park"),
    PLAIN,
    PLAIN,
    RIVER,
    town("Summit"),
  ],
  [
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    PLAIN,
    park("Riis Park"),
    PLAIN,
    PLAIN,
    town("Kedzie"),
    RIVER,
    PLAIN,
    town("Pulaski"),
    RIVER,
    PLAIN,
  ],
  [
    PLAIN,
    city("Dempster-Skokie", PURPLE, undefined, 3),
    PLAIN,
    PLAIN,
    RIVER,
    town("Irving Park"),
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
    city("Belmont", BLUE, undefined, 4),
    PLAIN,
    RIVER,
    park("Douglass Park"),
    RIVER,
    PLAIN,
    city("Midway", PURPLE, undefined, 2),
  ],
  [
    PLAIN,
    park("Evanston\nGolf Club"),
    town("Oakton"),
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    town("Medical District"),
    RIVER,
    town("Ashland"),
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    city("Damen", RED, undefined, 3),
    PLAIN,
    RIVER,
    park("Humboldt Park"),
    town("Diversey"),
    PLAIN,
    RIVER,
    RIVER,
    park("Norfolk\nSouthern\nAshland\nYard"),
    PLAIN,
    park("Marquette Park"),
  ],
  [
    city("Linden", PURPLE, undefined, 3),
    PLAIN,
    PLAIN,
    park("Rosehill\nCemetery"),
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
    RIVER,
    RIVER,
    town("Western"),
    PLAIN,
    town("63rd"),
    PLAIN,
  ],
  [
    PLAIN,
    town("Howard"),
    PLAIN,
    PLAIN,
    park("Graceland\nCemetery"),
    PLAIN,
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    PLAIN,
    city("Addison", BLUE, undefined, 3),
    PLAIN,
    PLAIN,
    THE_LOOP_NORTH,
    THE_LOOP_SOUTH,
    RIVER,
    RIVER,
    park("Washington Park"),
    RIVER,
    RIVER,
  ],
  [
    WATER,
    WATER,
    town("Wilmette"),
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    park("Grant Park"),
    RIVER,
    RIVER,
    town("Bronzeville"),
    PLAIN,
    PLAIN,
  ],
  [
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    park("Jackson Park"),
    PLAIN,
    city("Cottage Grove", RED, undefined, 4),
  ],
]);
