import { Good } from "../../engine/state/good";
import { SpaceType } from "../../engine/state/location_type";
import { LandData } from "../../engine/state/space";
import {
  BOTTOM,
  BOTTOM_LEFT,
  BOTTOM_RIGHT,
  TOP,
  TOP_LEFT,
  TOP_RIGHT,
} from "../../engine/state/tile";
import { duplicate } from "../../utils/functions";
import {
  city,
  grid,
  HILL,
  MOUNTAIN,
  PLAIN,
  town,
  UNPASSABLE,
} from "../factory";

const STREET: LandData = {
  type: SpaceType.STREET,
};

const LAKE: LandData = {
  type: SpaceType.LAKE,
};

export const map = grid([
  [
    ...duplicate(3, PLAIN),
    ...duplicate(6, STREET),
    city("Angrignon", Good.RED, [], 4),
    STREET,
  ],
  [
    city("Côte-Vertu", Good.PURPLE, [], 5),
    PLAIN,
    STREET,
    town("Namur"),
    PLAIN,
    city("Snowdon", Good.BLUE, [], 4),
    PLAIN,
    town("Vendôme"),
    STREET,
    PLAIN,
  ],
  [
    LAKE,
    ...duplicate(3, STREET),
    PLAIN,
    PLAIN,
    HILL,
    HILL,
    STREET,
    PLAIN,
    city("Lionel-Groulx", Good.RED, [], 3),
  ],
  [
    LAKE,
    PLAIN,
    { ...STREET, townName: "Canora" },
    PLAIN,
    PLAIN,
    town("Université de Montréal"),
    {
      ...MOUNTAIN,
      unpassableEdges: [TOP, TOP_LEFT, BOTTOM_LEFT, BOTTOM, BOTTOM_RIGHT],
    },
    city("Atwater", [Good.RED, Good.BLUE], [], 4),
    STREET,
    PLAIN,
  ],
  [
    town("Montmorency"),
    LAKE,
    PLAIN,
    STREET,
    town("Acadie"),
    HILL,
    {
      ...MOUNTAIN,
      unpassableEdges: [TOP, TOP_LEFT, TOP_RIGHT, BOTTOM],
    },
    PLAIN,
    STREET,
    town("Bonaventure"),
    LAKE,
  ],
  [
    PLAIN,
    LAKE,
    STREET,
    PLAIN,
    PLAIN,
    HILL,
    {
      ...MOUNTAIN,
      unpassableEdges: [TOP, TOP_RIGHT, BOTTOM_RIGHT, BOTTOM, BOTTOM_LEFT],
    },
    town("Place-de-Arts"),
    STREET,
    LAKE,
  ],
  [
    town("Cartier"),
    LAKE,
    city("Henri-Bourassa", Good.PURPLE, [], 3),
    STREET,
    PLAIN,
    city("Jean-Talon", Good.BLUE, [], 4),
    HILL,
    PLAIN,
    STREET,
    PLAIN,
    LAKE,
  ],
  [
    PLAIN,
    LAKE,
    STREET,
    PLAIN,
    PLAIN,
    HILL,
    town("Laurier"),
    PLAIN,
    city("Berri-Uqam", Good.YELLOW, [], 6),
    LAKE,
  ],
  [
    PLAIN,
    LAKE,
    PLAIN,
    STREET,
    PLAIN,
    town("Fabre"),
    PLAIN,
    PLAIN,
    PLAIN,
    LAKE,
    { ...LAKE, townName: "Jean-Drapeau" },
  ],
  [
    PLAIN,
    LAKE,
    { ...STREET, townName: "Saint Léonard" },
    ...duplicate(5, PLAIN),
    LAKE,
    { ...LAKE, terrainCost: 5 },
  ],
  [
    PLAIN,
    LAKE,
    PLAIN,
    STREET,
    PLAIN,
    city("Saint Michel", Good.BLUE, [], 3),
    PLAIN,
    PLAIN,
    town("Pie-Ix"),
    LAKE,
    city("Longueuil", Good.YELLOW, [], 4),
  ],
  [...duplicate(5, UNPASSABLE), ...duplicate(3, PLAIN), LAKE, PLAIN],
  [
    ...duplicate(6, UNPASSABLE),
    PLAIN,
    city("Assomption", Good.RED, [], 4),
    PLAIN,
    LAKE,
    PLAIN,
  ],
  [...duplicate(5, UNPASSABLE), ...duplicate(3, STREET), LAKE, STREET],
  [
    ...duplicate(6, UNPASSABLE),
    PLAIN,
    town("Honoré-Beuagrand"),
    PLAIN,
    LAKE,
    town("Boucherville"),
  ],
]);
