import z from "zod";

export enum GameKey {
  PUERTO_RICO = "puerto-rico",
  SOUTHERN_US = "southern-us",
  FOUR_CORNERS = "four-corners",
  BARBADOS = "barbados",
  BALKAN = "balkan",
  POLAND = "poland",
  TRISLAND = "trisland",
  PORTUGAL = "portugal",
  AUSTRALIA = "australia",
  DC_METRO = "dc-metro",
  SCANDINAVIA = "scandinavia",
  NEW_ENGLAND = "new-england",
  SCOTLAND = "scotland",
  ALABAMA_RAILWAYS = "alabama-railways",
  SICILY = "sicily",
  CYPRUS = "cyprus",
  DENMARK = "denmark",
  DETROIT = "detroit-bankruptcy",
  GERMANY = "germany",
  DISCO_INFERNO = "disco-inferno",
  INDIA_STEAM_BROTHERS = "india",
  IRELAND = "ireland",
  KOREA_WALLACE = "korea",
  LONDON = "london",
  MADAGASCAR = "madagascar",
  MONTREAL_METRO = "montreal-metro",
  REVERSTEAM = "reversteam",
  ST_LUCIA = "st-lucia",
  PITTSBURGH = "pittsburgh",
  MOON = "moon",
  RUST_BELT = "rust-belt",
  SOUL_TRAIN = "soul-train",
  SWEDEN = "SwedenRecycling",
  JAMAICA = "jamaica",
  HEAVY_CARDBOARD = "heavy-cardboard",
  CHESAPEAKE_AND_OHIO = "chesapeake-and-ohio",
  CALIFORNIA_GOLD_RUSH = "california-gold-rush",
  UNION_PACIFIC_EXPRESS = "union-pacific-express",
  RUST_BELT_EXPRESS = "rust-belt-express",
  CHICAGO_SPEAKEASY = "chicago-speakeasy",
  BELGIUM = "belgium",
  EASTERN_US_AND_CANADA = "eastern-us-and-canada",
  DOUBLE_BASE_USA = "double-base-usa",
  CHICAGO_L = "chicago-l",
}

export const GameKeyZod = z.nativeEnum(GameKey);
