import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import {
  black,
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  white,
} from "../factory";
import z from "zod";
import { Direction, DirectionZod } from "../../engine/state/tile";
import { SpaceStyle } from "../../engine/state/location_style";
import { LandData } from "../../engine/state/space";

export const JapanMapData = z.object({
  waterCrossing: z.boolean().optional(),
  halfWaterSide: DirectionZod.optional(),
});
export type JapanMapData = z.infer<typeof JapanMapData>;

const WATER_CROSSING = {
  ...PLAIN,
  style: SpaceStyle.WATER,
  mapSpecific: {
    waterCrossing: true,
  },
};
function halfWater(waterSide: Direction): LandData {
  return {
    ...PLAIN,
    mapSpecific: {
      halfWaterSide: waterSide,
    },
  };
}

export const map = grid([
  [UNPASSABLE, UNPASSABLE, town("Wakkanai")],
  [UNPASSABLE, PLAIN, RIVER],
  [UNPASSABLE, UNPASSABLE, RIVER, PLAIN],
  [UNPASSABLE, PLAIN, town("Asahikawa"), RIVER, PLAIN],
  [
    UNPASSABLE,
    city("Abashiri", RED, black(1), 3),
    MOUNTAIN,
    RIVER,
    city("Sapporo", PURPLE, black(2), 2),
    PLAIN,
    PLAIN,
  ],
  [MOUNTAIN, PLAIN, town("Obihiro"), MOUNTAIN, PLAIN, town("Hakodate"), PLAIN],
  [
    UNPASSABLE,
    town("Kushiro"),
    PLAIN,
    MOUNTAIN,
    PLAIN,
    WATER_CROSSING,
    WATER_CROSSING,
    WATER_CROSSING,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    city("Aomori", BLUE, black(3), 2),
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    MOUNTAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    town("Morioka"),
    PLAIN,
    PLAIN,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Shimonoseki"),
    WATER_CROSSING,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    town("Niigata"),
    RIVER,
    PLAIN,
    city("Toyama", YELLOW, white(3), 2),
    PLAIN,
    PLAIN,
    town("Tsuyama"),
    MOUNTAIN,
    town("Hiroshima"),
    PLAIN,
    WATER_CROSSING,
    city("Fukuoka", YELLOW, white(5), 2),
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    city("Sendai", PURPLE, black(4), 2),
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    halfWater(Direction.BOTTOM_RIGHT),
    WATER_CROSSING,
    WATER_CROSSING,
    PLAIN,
    MOUNTAIN,
    town("Nagasaki"),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Nagoya"),
    PLAIN,
    city("Osaka", BLUE, [white(1), white(2)], 2),
    WATER_CROSSING,
    RIVER,
    city("Matsuyama", RED, white(4), 2),
    WATER_CROSSING,
    town("Nobeoka"),
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    town("Hitachi"),
    RIVER,
    city("Tokyo", RED, [black(5), black(6)], 2),
    MOUNTAIN,
    MOUNTAIN,
    WATER_CROSSING,
    PLAIN,
    WATER_CROSSING,
    town("Takamatsu"),
    RIVER,
    PLAIN,
    WATER_CROSSING,
    PLAIN,
    city("Kagoshima", BLUE, white(6), 3),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    RIVER,
    halfWater(Direction.TOP_RIGHT),
    town("Shizuoka"),
  ],
]);
