import {
  black,
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  WATER,
  white,
} from "../factory";
import z from "zod";
import { CityData, LandData } from "../../engine/state/space";
import { BLACK, BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { SpaceType } from "../../engine/state/location_type";

export const MinasGeraesMapData = z.object({
  miningTown: z.boolean().optional(),
  ouroPretoCubeSource: z.boolean().optional(),
  ouroPretoCost: z.number().optional(),
});
export type MinasGeraesMapData = z.infer<typeof MinasGeraesMapData>;

function miningTown(name: string): LandData {
  return {
    ...town(name),
    mapSpecific: {
      miningTown: true,
    },
  };
}

export const OURO_PRETO_SAME_CITY = 1;

const OURO_PRETO: CityData = {
  type: SpaceType.CITY,
  sameCity: OURO_PRETO_SAME_CITY,
  color: [],
  name: "Ouro Preto",
  goods: [],
  onRoll: [],
  startingNumCubes: 0,
};

export const map = grid([
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city("", RED, white(2), 2),
    PLAIN,
    PLAIN,
    MOUNTAIN,
    city("", BLACK, white(6), 2),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    RIVER,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    WATER,
    town(""),
    MOUNTAIN,
    miningTown(""),
    MOUNTAIN,
    PLAIN,
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    miningTown(""),
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    city("", BLUE, white(5), 2),
  ],
  [
    city("", BLACK, white(1), 2),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("", YELLOW, white(4), 2),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    MOUNTAIN,
    PLAIN,
    MOUNTAIN,
    PLAIN,
    town(""),
    PLAIN,
    city("", PURPLE, white(3), 2),
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    RIVER,
    PLAIN,
    town(""),
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    {
      ...OURO_PRETO,
      mapSpecific: {
        ouroPretoCubeSource: true,
      },
    },
    {
      ...OURO_PRETO,
      mapSpecific: {
        ouroPretoCost: 0,
      },
    },
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    town(""),
    WATER,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
    PLAIN,
    city("", BLUE, black(2), 2),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    RIVER,
    RIVER,
    RIVER,
    city("", YELLOW, black(3), 2),
    PLAIN,
    town(""),
    PLAIN,
    PLAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    miningTown(""),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city("", RED, black(4), 2),
    MOUNTAIN,
    miningTown(""),
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    city("", PURPLE, black(5), 2),
    PLAIN,
    town(""),
    MOUNTAIN,
    miningTown(""),
    MOUNTAIN,
    city("", BLACK, black(1), 2),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city("", BLACK, black(6), 2),
    MOUNTAIN,
    PLAIN,
    RIVER,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
  ],
]);
