import { BLACK, BLUE, RED, YELLOW } from "../../engine/state/good";
import { SpaceData } from "../../engine/state/space";
import { duplicate } from "../../utils/functions";
import {
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  white,
} from "../factory";

export const map = grid<SpaceData>([
  [...duplicate(4, UNPASSABLE), PLAIN, city("", BLUE, white(1), 4)],
  [...duplicate(3, UNPASSABLE), PLAIN, MOUNTAIN, MOUNTAIN, PLAIN],
  [...duplicate(3, UNPASSABLE), town(""), PLAIN, MOUNTAIN, PLAIN, town("")],
  [...duplicate(3, UNPASSABLE), ...duplicate(4, RIVER)],
  [...duplicate(3, UNPASSABLE), PLAIN, PLAIN, town(""), PLAIN, PLAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    town(""),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town(""),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    MOUNTAIN,
    city("", YELLOW, white(2), 4),
    { ...MOUNTAIN, terrainCost: 6 },
    city("", YELLOW, white(3), 4),
    MOUNTAIN,
    PLAIN,
  ],
  [
    town(""),
    RIVER,
    PLAIN,
    MOUNTAIN,
    { ...MOUNTAIN, terrainCost: 6 },
    { ...MOUNTAIN, terrainCost: 6 },
    MOUNTAIN,
    PLAIN,
    RIVER,
    town(""),
  ],
  [
    PLAIN,
    PLAIN,
    RIVER,
    town(""),
    MOUNTAIN,
    city("", YELLOW, white(4), 4),
    MOUNTAIN,
    town(""),
    RIVER,
    PLAIN,
    PLAIN,
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
  ],
  [
    city("", BLACK, white(5), 4),
    MOUNTAIN,
    PLAIN,
    RIVER,
    PLAIN,
    town(""),
    PLAIN,
    RIVER,
    PLAIN,
    MOUNTAIN,
    city("", RED, white(6), 4),
  ],
  [PLAIN, PLAIN, town(""), ...duplicate(4, UNPASSABLE), town(""), PLAIN],
]);
