import { BLACK, BLUE, RED, YELLOW } from "../../engine/state/good";
import { SpaceData } from "../../engine/state/space";
import { duplicate } from "../../utils/functions";
import {
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  white,
} from "../factory";

export const map = grid<SpaceData>([
  [...duplicate(4, UNPASSABLE), PLAIN, city("A", BLUE, white(1))],
  [...duplicate(3, UNPASSABLE), PLAIN, MOUNTAIN, MOUNTAIN, PLAIN],
  [...duplicate(3, UNPASSABLE), town("B"), PLAIN, MOUNTAIN, PLAIN, town("C")],
  [...duplicate(3, UNPASSABLE), ...duplicate(4, RIVER)],
  [...duplicate(3, UNPASSABLE), PLAIN, PLAIN, town("D"), PLAIN, PLAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    town("E"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("F"),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    MOUNTAIN,
    city("G", YELLOW, white(2)),
    { ...MOUNTAIN, terrainCost: 6 },
    city("H", YELLOW, white(3)),
    MOUNTAIN,
    PLAIN,
  ],
  [
    town("I"),
    RIVER,
    PLAIN,
    MOUNTAIN,
    { ...MOUNTAIN, terrainCost: 6 },
    { ...MOUNTAIN, terrainCost: 6 },
    MOUNTAIN,
    PLAIN,
    RIVER,
    town("J"),
  ],
  [
    PLAIN,
    PLAIN,
    RIVER,
    town("K"),
    MOUNTAIN,
    city("L", YELLOW, white(4)),
    MOUNTAIN,
    town("M"),
    RIVER,
    PLAIN,
    PLAIN,
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
  ],
  [
    city("N", BLACK, white(5)),
    MOUNTAIN,
    PLAIN,
    RIVER,
    PLAIN,
    town("O"),
    PLAIN,
    RIVER,
    PLAIN,
    MOUNTAIN,
    city("P", RED, white(6)),
  ],
  [PLAIN, PLAIN, town("Q"), ...duplicate(4, UNPASSABLE), town("R"), PLAIN],
]);
