import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { SpaceData } from "../../engine/state/space";
import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  WATER,
  white,
} from "../factory";

export const map = grid<SpaceData>([
  [
    city("Bragança", YELLOW, black(4)),
    PLAIN,
    UNPASSABLE,
    UNPASSABLE,
    town("Monção"),
    PLAIN,
    ...duplicate(5, WATER),
  ],
  [
    PLAIN,
    town("Chaves"),
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    town("Viana do Castelo"),
    ...duplicate(5, WATER),
  ],
  [...duplicate(6, PLAIN), ...duplicate(5, WATER)],
  [
    RIVER,
    city("Vila Real", RED, black(3)),
    RIVER,
    RIVER,
    city("Porto", BLUE, black(2)),
    WATER,
    ...duplicate(5, WATER),
  ],
  [UNPASSABLE, ...duplicate(5, PLAIN), WATER, ...duplicate(4, WATER)],
  [
    town("Guarda"),
    MOUNTAIN,
    RIVER,
    RIVER,
    RIVER,
    WATER,
    WATER,
    ...duplicate(4, WATER),
  ],
  [
    UNPASSABLE,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Coimbra"),
    RIVER,
    WATER,
    WATER,
    ...duplicate(3, WATER),
  ],
  [
    MOUNTAIN,
    town("Castelo Branco"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    WATER,
    WATER,
    ...duplicate(3, WATER),
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    RIVER,
    city("Entroncamento", RED, black(1)),
    PLAIN,
    PLAIN,
    city("Leiria", YELLOW, white(4)),
    WATER,
    WATER,
    ...duplicate(2, WATER),
  ],
  [
    UNPASSABLE,
    town("Portalegre"),
    RIVER,
    RIVER,
    RIVER,
    PLAIN,
    PLAIN,
    WATER,
    ...duplicate(3, WATER),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Almeirim"),
    RIVER,
    PLAIN,
    WATER,
    WATER,
    WATER,
    WATER,
  ],
  [
    UNPASSABLE,
    town("Elvas"),
    PLAIN,
    PLAIN,
    PLAIN,
    WATER,
    city("Lisboa", RED, white(3)),
    WATER,
    WATER,
    WATER,
    city("Açores", BLUE, [], 3),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    PLAIN,
    PLAIN,
    town("Setúbal"),
    RIVER,
    WATER,
    ...duplicate(3, WATER),
  ],
  [
    town("Barrancos"),
    PLAIN,
    city("Beja", PURPLE, white(2)),
    PLAIN,
    RIVER,
    WATER,
    WATER,
    ...duplicate(4, WATER),
  ],
  [
    UNPASSABLE,
    PLAIN,
    RIVER,
    PLAIN,
    RIVER,
    town("Sines"),

    WATER,
    ...duplicate(4, WATER),
  ],
  [UNPASSABLE, UNPASSABLE, RIVER, PLAIN, PLAIN, PLAIN, ...duplicate(5, WATER)],
  [
    UNPASSABLE,
    UNPASSABLE,
    RIVER,
    MOUNTAIN,
    PLAIN,
    MOUNTAIN,
    ...duplicate(5, WATER),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    city("Faro", YELLOW, white(1)),
    PLAIN,
    town("Sagres"),
    ...duplicate(4, WATER),
    city("Madeira", PURPLE, [], 3),
  ],
]);
