import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { black, city, grid, PLAIN, UNPASSABLE, white } from "../factory";

export const map = grid([
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city("Bruges", RED, white(6), 2),
    PLAIN,
    city("Oostende", YELLOW, white(5), 2),
  ],
  [UNPASSABLE, UNPASSABLE, UNPASSABLE, PLAIN, PLAIN, PLAIN, PLAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    city("Gent", BLUE, white(4), 2),
    PLAIN,
    PLAIN,
  ],
  [UNPASSABLE, UNPASSABLE, PLAIN, PLAIN, PLAIN, PLAIN, PLAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    city("Antwerpen", PURPLE, black(4), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    city("Mons", BLUE, white(3), 2),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    city("Bruxelles", RED, white(1), 2),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Charleroi", BLUE, white(2), 2),
    PLAIN,
  ],
  [PLAIN, PLAIN, city("Leuven", BLUE, black(3), 2), PLAIN, PLAIN, PLAIN, PLAIN],
  [
    UNPASSABLE,
    city("Maastricht", RED, black(1), 2),
    PLAIN,
    PLAIN,
    city("Namur", RED, black(5), 2),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    city("Liege", YELLOW, black(2), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    UNPASSABLE,
  ],
  [UNPASSABLE, UNPASSABLE, PLAIN, PLAIN, PLAIN, PLAIN, PLAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Arlen & Luxembourg", PURPLE, black(6), 2),
  ],
]);
