import { Good } from "../../engine/state/good";
import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  grid,
  DARK_MOUNTAIN,
  UNPASSABLE,
  SWAMP,
  PLAIN,
  town,
  WATER,
  white,
} from "../factory";

export const map = grid([
  [...duplicate(2, WATER), town("Szczecin"), ...duplicate(4, PLAIN)],
  [
    WATER,
    ...duplicate(2, PLAIN),
    town("Gorzow"),
    PLAIN,
    town("Zielona Gora"),
    PLAIN,
    town("Luban"),
  ],
  [WATER, ...duplicate(8, PLAIN)],
  [
    town("Koszalin"),
    ...duplicate(6, PLAIN),
    city("Wroclaw", Good.YELLOW, black(6), 3),
    DARK_MOUNTAIN,
  ],
  [
    ...duplicate(5, PLAIN),
    city("Poznan", Good.RED, white(3), 2),
    ...duplicate(3, PLAIN),
    DARK_MOUNTAIN,
  ],
  [
    PLAIN,
    town("Chojnice"),
    PLAIN,
    city("Bydgoszcz", Good.BLUE, white(2), 2),
    ...duplicate(4, PLAIN),
    town("Opole"),
    DARK_MOUNTAIN,
  ],
  [
    city("Gdansk", Good.PURPLE, white(1), 3),
    ...duplicate(9, PLAIN),
    DARK_MOUNTAIN,
  ],
  [
    ...duplicate(9, PLAIN),
    city("Katowice", Good.BLUE, black(5), 2),
    DARK_MOUNTAIN,
  ],
  [
    UNPASSABLE,
    ...duplicate(5, PLAIN),
    city("Lodz", Good.RED, white(5), 2),
    ...duplicate(4, PLAIN),
  ],
  [
    PLAIN,
    town("Olsztyn"),
    ...duplicate(8, PLAIN),
    city("Krakow", Good.RED, black(4), 2),
  ],
  [
    UNPASSABLE,
    PLAIN,
    SWAMP,
    PLAIN,
    PLAIN,
    city("Warsaw", Good.BLUE, white(4), 3),
    PLAIN,
    PLAIN,
    city("Kielce", Good.BLUE, white(6), 2),
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    SWAMP,
    SWAMP,
    town("Ostroteka"),
    ...duplicate(6, PLAIN),
    DARK_MOUNTAIN,
  ],
  [
    UNPASSABLE,
    town("Olecko"),
    SWAMP,

    ...duplicate(7, PLAIN),
    city("Rzeszow", Good.YELLOW, black(3), 2),
  ],
  [
    ...duplicate(5, PLAIN),
    town("Lukow"),
    PLAIN,
    city("Lublin", Good.RED, black(2), 2),
    ...duplicate(2, PLAIN),
    DARK_MOUNTAIN,
  ],
  [
    UNPASSABLE,
    ...duplicate(2, PLAIN),
    city("Bialystok", Good.PURPLE, black(1), 2),
    ...duplicate(6, PLAIN),
  ],
]);
