import { Good } from "../../engine/state/good";
import { duplicate } from "../../utils/functions";
import {
  black,
  city,
  grid,
  MOUNTAIN,
  UNPASSABLE,
  SWAMP,
  PLAIN,
  town,
  WATER,
  white,
} from "../factory";

export const map = grid([
  [...duplicate(3, WATER), town("Szczecin"), ...duplicate(4, PLAIN)],
  [
    ...duplicate(2, WATER),
    ...duplicate(2, PLAIN),
    town("Gorzow"),
    PLAIN,
    town("Zielona Gora"),
    PLAIN,
    town("Luban"),
  ],
  [...duplicate(2, WATER), ...duplicate(8, PLAIN)],
  [
    WATER,
    town("Town 5"),
    ...duplicate(6, PLAIN),
    city("City1", Good.YELLOW, black(6)),
    MOUNTAIN,
  ],
  [
    WATER,
    ...duplicate(5, PLAIN),
    city("City1", Good.RED, white(3)),
    ...duplicate(3, PLAIN),
    MOUNTAIN,
  ],
  [
    WATER,
    PLAIN,
    town("Town 6"),
    PLAIN,
    city("City1", Good.BLUE, white(2)),
    ...duplicate(4, PLAIN),
    town("Town 7"),
    MOUNTAIN,
  ],
  [
    WATER,
    city("City1", Good.PURPLE, white(1)),
    ...duplicate(9, PLAIN),
    MOUNTAIN,
  ],
  [WATER, ...duplicate(9, PLAIN), city("City1", Good.BLUE, black(5)), MOUNTAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    ...duplicate(5, PLAIN),
    city("City", Good.RED, black(5)),
    ...duplicate(4, PLAIN),
  ],
  [
    UNPASSABLE,
    PLAIN,
    town("town 8"),
    ...duplicate(8, PLAIN),
    city("City", Good.RED, black(4)),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    SWAMP,
    PLAIN,
    PLAIN,
    city("City", Good.BLUE, black(5)),
    PLAIN,
    PLAIN,
    city("City", Good.BLUE, black(6)),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    SWAMP,
    SWAMP,
    town("town 9"),
    ...duplicate(6, PLAIN),
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    town("town 9"),
    SWAMP,

    ...duplicate(7, PLAIN),
    city("City", Good.YELLOW, black(3)),
  ],
  [
    UNPASSABLE,
    ...duplicate(5, PLAIN),
    town("town 9"),
    PLAIN,
    city("City", Good.RED, black(2)),
    ...duplicate(2, PLAIN),
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    ...duplicate(2, PLAIN),
    city("City", Good.PURPLE, black(1)),
    ...duplicate(6, PLAIN),
  ],
]);
