import {black, city, grid, HILL, MOUNTAIN, plain, PLAIN, town, UNPASSABLE, WATER, white,} from "../factory";
import {BLUE, PURPLE, RED, YELLOW} from "../../engine/state/good";
import {SpaceStyle} from "../../engine/state/location_style";
import {LandData} from "../../engine/state/space";
import {Direction} from "../../engine/state/tile";

const FJORD = {
  ...MOUNTAIN,
  style: SpaceStyle.FJORD,
};

function fjordTown(townName: string): LandData {
  return { ...MOUNTAIN, townName: townName, style: SpaceStyle.FJORD };
}
function hillTown(townName: string): LandData {
  return { ...HILL, townName: townName };
}

function ferryTown(name: string, ferryLinks: Array<{direction: Direction, city: string}>): LandData {
  return {
    ...town(name),
    mapSpecific: {
      ferryLinks: ferryLinks,
    },
  };
}

export const map = grid([
  [
    UNPASSABLE,
    plain({ terrainCost: 3 }),
    city("Göteborg", [PURPLE], white(1), 2),
    WATER,
    WATER,
    WATER,
    PLAIN,
    town("Hirtshals"),
    WATER,
    WATER,
    city("Europe", [], undefined, 0),
    WATER,
  ],
  [
    PLAIN,
    plain({ terrainCost: 3 }),
    WATER,
    WATER,
    WATER,
    city("Frederikshaven", [YELLOW], white(2), 2),
    PLAIN,
    PLAIN,
    WATER,
    WATER,
    WATER,
  ],
  [
    UNPASSABLE,
    town("Halmstad"),
    WATER,
    WATER,
    WATER,
    WATER,
    HILL,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    WATER,
  ],
  [
    PLAIN,
    PLAIN,
    WATER,
    WATER,
    WATER,
    WATER,
    hillTown("Aalborg"),
    HILL,
    FJORD,
    fjordTown("Thisted"),
    PLAIN,
  ],
  [
    UNPASSABLE,
    plain({ terrainCost: 4 }),
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    PLAIN,
    HILL,
    PLAIN,
    FJORD,
    fjordTown("Thyborøn"),
  ],
  [
    city("Malmö", [BLUE], white(4), 2),
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    town("Randers"),
    HILL,
    city("Viborg", [BLUE], white(3), 2),
    FJORD,
    FJORD,
  ],
  [
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    town("Grenå"),
    PLAIN,
    HILL,
    HILL,
    HILL,
    town("Ringkøbing"),
    FJORD,
  ],
  [
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    PLAIN,
    city("Århus", [YELLOW], white(5), 2),
    HILL,
    HILL,
    HILL,
    PLAIN,
  ],
  [
    WATER,
    PLAIN,
    FJORD,
    WATER,
    WATER,
    WATER,
    WATER,
    HILL,
    HILL,
    PLAIN,
    PLAIN,
    WATER,
  ],
  [
    city("Copenhagen", [YELLOW], black(2), 2),
    PLAIN,
    FJORD,
    PLAIN,
    city("Kalundborh", [RED], black(1), 2),
    WATER,
    WATER,
    hillTown("Vejle"),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    WATER,
    WATER,
    town("Roskilde"),
    HILL,
    PLAIN,
    WATER,
    PLAIN,
    PLAIN,
    HILL,
    PLAIN,
    city("Ribe", [PURPLE], white(6), 2),
    PLAIN,
  ],
  [
    WATER,
    PLAIN,
    HILL,
    ferryTown("Korsør", [{direction: Direction.BOTTOM, city: "Nyborg"}, {direction: Direction.TOP_RIGHT, city: "Nykøbing"}]),
    WATER,
    city("Nyborg", [RED], black(3), 2),
    HILL,
    WATER,
    PLAIN,
    PLAIN,
    WATER,
  ],
  [
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    PLAIN,
    WATER,
    city("Åbenrå", [PURPLE], black(4), 2),
    PLAIN,
    PLAIN,
    WATER,
  ],
  [
    WATER,
    WATER,
    PLAIN,
    FJORD,
    ferryTown("Rødbyhavn", [{direction: Direction.TOP_LEFT, city: "Nyborg"}, {direction: Direction.BOTTOM_RIGHT, city: "Puttgarden"}]),
    WATER,
    WATER,
    plain({ terrainCost: 3 }),
    plain({ terrainCost: 3 }),
    plain({ terrainCost: 3 }),
    WATER,
  ],
  [
    WATER,
    WATER,
    city("Nykøbing", [RED], black(5), 2),
    PLAIN,
    PLAIN,
    WATER,
    WATER,
    PLAIN,
    town("Flensburg"),
    PLAIN,
    WATER,
    WATER,
  ],
  [
    plain({ terrainCost: 4 }),
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    FJORD,
    FJORD,
    PLAIN,
    PLAIN,
    WATER,
  ],
  [
    UNPASSABLE,
    plain({ terrainCost: 4 }),
    ferryTown("Warnemünde", [{direction: Direction.BOTTOM_LEFT, city: "Nykøbing"}]),
    WATER,
    WATER,
    city("Puttgarden", [PURPLE], black(6), 2),
    plain({ terrainCost: 3 }),
    town("Kiel"),
    PLAIN,
    town("Schleswig"),
    FJORD,
    WATER,
  ],
]);
